### ISSUE TITLE
enhance arche-metadata

### ISSUE THREAD

**Issue by csae8092** [dQIOG/pez-letters#9]
* basic ARCHE-Ingestion workflow set up;
* formal minimal metadata requirements are fulfilled (https://id.acdh.oeaw.ac.at/pez-briefe) 

## ToDo: better Meta-Data especially on collection Level

* check here for an overview of which properties could be added (https://arche.acdh.oeaw.ac.at/browser/api/rootTable/en?_format=html), *OR*  is recommended
* metadata could (ideally) be edited directly in [arche_constants.ttl](https://github.com/dQIOG/pez-letters/blob/main/arche_seed_files/arche_constants.ttl) or provided in some other format

## ToDo: make TEI files valid

* #8 
* #6 
* #7

**Comment by dasch124** [comment]
Letter 1 to 478 `acdh:hasSource <https://id.acdh.oeaw.ac.at/pez-briefe/vol-01-2010>`
Letter 478 to 1035 `acdh:hasSource < <https://id.acdh.oeaw.ac.at/pez-briefe/vol-02-2015>` 

https://github.com/dQIOG/pez-letters/issues/14

**Comment by csae8092** [comment]
> Letter 1 to 478 `acdh:hasSource <https://id.acdh.oeaw.ac.at/pez-briefe/vol-01-2010>` Letter 478 to 1035 `acdh:hasSource < <https://id.acdh.oeaw.ac.at/pez-briefe/vol-02-2015>`

ARCHE-Schema only knows [acdh:isSourceOf](https://acdh-oeaw.github.io/arche-schema/#isSourceOf)

**Comment by dasch124** [comment]
true, it's the other way round

**Comment by dasch124** [comment]
- [ ] acdh:hasNextItem = ``//tei:ptr[@type="next"]/replace(@target, "letter:(\d+)", "https://id.acdh.oeaw.ac.at/pez-briefe/pez_{$1}.xml)")``
- [ ] acdh:hasTitle = `concat(if (//tei:gap[@reason='inferred letter']) then '[' else '',//tei:idno[@type='pezEd'], if (//tei:gap[@reason='inferred letter']) then '] ' else ' ', //tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:title[not(@level) or @level='a'])`
- [ ] `if (//tei:idno[@type='pezEd']/xs:integer(.) le 478) then concat("<https://id.acdh.oeaw.ac.at/pez-briefe/vol-01-2010> acdh:isSourceOf <https://id.acdh.oeaw.ac.at/pez-briefe/pez_",//tei:idno[@type='pezEd'],".xml") else concat("<https://id.acdh.oeaw.ac.at/pez-briefe/vol-02-2015> acdh:isSourceOf <https://id.acdh.oeaw.ac.at/pez-briefe/pez_",//tei:idno[@type='pezEd'],".xml>")`
- [ ] Please also copy the ODD & RNG to a dedicated Colllection

**Comment by dasch124** [comment]
I wonder whether we couldn't source the mapping from the TEI docs themselves, by introducing an `@ana` attribute anywhere on `<resp>`, e.g.

```xml
<respStmt>
         <resp ana="acdh:hasContributor">Postprocessing</resp>
         <orgName>Rechercheagentur Patrick Fiska</orgName>
         <persName ref="https://orcid.org/0000-0002-0118-0811">Dario Kampkaspar</persName>
</respStmt>
```

* acdh:hasCreator = `//tei:respStmt[tei:resp/@ana = 'arche:hasCreator']/*/@ref`
* acdh:hasContributor = `//tei:respStmt[tei:resp/@ana = 'arche:hasContributor']/*/@ref`

**Comment by csae8092** [comment]
feel free to add as much information into the tei; also next/previous; a proper arche-title or the source because this makes arche-md creation much easier

because something like this 
```
acdh:hasTitle = concat(if (//tei:gap[@reason='inferred letter']) then '[' else '',//tei:idno[@type='pezEd'], if (//tei:gap[@reason='inferred letter']) then '] ' else ' ', //tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:title[not(@level) or @level='a'])
```
smells like bad data

**Comment by dasch124** [comment]
it's because the data is more granular than its representation in the title

`TEI/@n` contains the letter number as a a pretty integer; but in the title we would like to render the letter number in square brackets if the letter has not been preserved, that's why the `<gap>`; I don't want to hard-code these square brackets into `@n`, that's why the logic is needed.
